name: Angular CI (Reusable)

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fox repository
        uses: actions/checkout@v4
        with:
          repository: DannyKarouw/fox-security
          ref: develop

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Run unit tests
        run: npm run test

      - name: Build Angular app
        run: npm run build
